Fix: RSS and Atom Feeds
hashobject/perun pull request #251
Opened 2020-10-21 19:37 UTC by munen

Both Atom and RSS feeds had some issues. This PR is not a perfect solution, but it improves the situation quite a bit.

Changes for Atom:

- Atom feeds were not valid before. The rather old version of `clojure.data.xml` library would render `<feed xmlns:a="http://www.w3.org/2005/Atom">` instead of `<feed xmlns="http://www.w3.org/2005/Atom">` (notice the `:a` namespace). Whilst this doesn't look like a huge issue, it leads to various issues:

  - https://validator.w3.org/feed/ would not deem the feed valid

![image](https://user-images.githubusercontent.com/505721/96772798-f1ca4100-13e3-11eb-9517-c9b8c4553100.png)

  - The feed would be rejected by various feed readers (i.e. Thunderbird and Miniflux).

![image](https://user-images.githubusercontent.com/505721/96772972-2fc76500-13e4-11eb-837a-cde59c0471a7.png)

  - Other feed readers would show 'random' errors. For example feedbin.com will skip various posts whilst showing others.

The issue was not trivial to fix, because the docs of `clojure.data.xml` state namespaces as a new feature. And this new syntax would not work on the old version. Finally, I realized that upgrading to the current version would give me access to said syntax. And since atom.clj is not specifying any namespace, now none is rendered and will make the Atom feed valid.

Unfortunately, the tests are now breaking. They run very slow for me and I don't know how to debug them. Hence, I left them broken (apologies). Simply reverting the clojure.data.xml version will make the tests run again, but then the feed will not be valid.

If someone teaches me how to run perun with Cider so that I can do some debugging or run just one test, I'd be happy to give that a shot at some point.

Changes for RSS:

Firstly, they are not nearly as huge as the Atom issue(;

- The sort order of posts in many feed readers was random, because the sort order happend on the name of the week day instead of the date. There's more information inline in the code.

- It would be nice to have included the complete content of the post into the RSS feed, but I'm lacking the necessary knowledge to do that in Perun. The `:content` attribute for a post is not accessible in rss.clj; it is in atom.clj, though. I've added the necessary boilerplate.

- It would be nice to support multiple authors, but since the used clj-rss library does not support it, I've only left informative comments for the next dev checking that out.

- The RSS spec allows for "author" and "author-email" to be given as meta-date. I've added the specified syntax.

---

As a result, both RSS and Atom feeds for 200ok.ch are valid now:

- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2F200ok.ch%2Fatom.xml
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2F200ok.ch%2Frss.xml

Both still have recommondations that could be addressed, but at least they are valid and work for all tested feed readers - including the ones that silently didn't work for one reason or another(;

2020-10-21 22:19 UTC, allentiak commented
Thanks for the feature, @munen !

That being said, I think merging it with a broken test would be a pity...
If you want, we could meet to do some pair programming in the upcoming weeks, so we give it a look? Maybe we can make it work...
I haven't worked on this code for a long time...

2020-10-21 22:20 UTC, allentiak requested changes
(See [conversation message](https://github.com/hashobject/perun/pull/251#issuecomment-713909511)

2020-10-22 07:05 UTC, munen commented
Thank you for inviting me to this repository @allentiak :pray: 

> That being said, I think merging it with a broken test would be a pity...

I agree. It's not even just a broken test, that I probably could have fixed. It's crashing with a stack trace. Hence, debugging would be benefitial.

For our site (200ok.ch), I've received mails from readers that they couldn't read the blog via Atom (which we link to in the header). My main priority was to get that to work and then to see if there's interest upstream - which I am very happy to see(;

> If you want, we could meet to do some pair programming in the upcoming weeks, so we give it a look? Maybe if we work together we can make it work...

That's a very kind offer which I'd happily take you up on :pray: 

Are you currently in UTC-3? If so, then we are five hours apart (I'm at UTC+2). I'm currently doing mostly product work, so I don't have too many strict appointments. For example, I could do today or tomorrow in our afternoon, so your morning.

> I haven't worked on this code for a long time...

No worries. I know that you've reached out for help on this project. I haven't stepped up for two reasons mainly: There's lots of other stuff (I'm not the only one here, though), and I'm not what I personally would call familiar with boot or the Perun code base. Having said that, we've invested quite a bit into building 200ok.ch based on Perun. So I do have a high motivation to fix bugs and keep the project going, because otherwise at some point we would have to migrate away. And rebuilding doesn't always/often make things better(;

2020-10-22 18:11 UTC, allentiak commented
@munen Thanks for your message! I've replied you privately.

2020-11-01 12:48 UTC, munen commented
Thanks to an answer of [Alex Miller himself on SO](https://stackoverflow.com/questions/64611482/how-to-generate-a-xml-without-a-namespace-with-the-latest-version-of-org-clojure/64615916#64615916), the tests now run and we have a feed without an auto-generated prefix.

However, the feed arguably has become become valid, but moved further into the invalid:

![image](https://user-images.githubusercontent.com/505721/97803188-bbdd5600-1c48-11eb-986a-14d441344e70.png)

2020-11-01 13:06 UTC, munen commented
I have updated the question on SO and answered Mr. Alex Miller: https://stackoverflow.com/questions/64611482/how-to-generate-a-xml-without-a-namespace-with-the-latest-version-of-org-clojure

2020-11-01 19:06 UTC, allentiak commented
I saw you got some interesting replies to your question ;-)

2020-11-01 19:12 UTC, munen commented
> I saw you got some interesting replies to your question ;-)

Yes, so :crossed_fingers: that it'll get resolved there, too(;

2020-11-01 19:14 UTC, allentiak commented
> we have a feed without an auto-generated prefix.

@munen That certainly *is* progress :-)


> However, the feed [...] moved further into the invalid

@munen I saw the error messages, but... What do you mean by this, exactly?

2020-11-01 19:40 UTC, munen commented
> @munen I saw the error messages, but... What do you mean by this, exactly? Is this the validator bug you mentioned in your SO question?

I wouldn't call it a 'validator bug' which implies in a bug in the validator, but yes I mean the update that I've added to the SO question where I go into further detail. With the proposed fix from Alex Miller, the feed actually has more errors, even though the first error went away.

2020-11-01 19:47 UTC, allentiak commented
I see. Thanks for the explanation, @munen!

2020-11-02 08:04 UTC, munen commented
Tests are green now:

> Ran 6 tests, 94 assertions, 0 failures, 0 errors.

Also, both RSS and Atom feeds are valid.

This PR is ready to merge.

2020-11-02 17:00 UTC, allentiak approved these changes

2020-11-02 17:00 UTC, merged

2020-11-02 17:02 UTC, allentiak commented
@munen  Thank you very much for your hard work!

Merged :-)